name: XMLGenerator
version: 0.0.1
author: kroest
main: me.kroest.xmlgenerator.Main
api-version: 1.13
commands:
   map:
      description: Generate a new XML with a given name.
      usage: /map <mapname>

   region:
      description: Generate a new region. Ensure you added teams before you try to apply a filter on a team.
      usage: /region <shape> <filters> <teams/all>

   objective:
      description: Generate an objective owned by a certain team with the currently selected region, with posslble color atttribute if type equals wool/flag.
      usage: /objective <type> <team>

   team:
      description: Add/remove a team.
      usage: /team <add/remove> <name>

   spawn:
      description: Add a spawnpoint for a specified team.
      usage: /spawn <team>

   kit:
      description: Creates a kit of the last set inventory, for the specified team.
      usage: /kit <team>